"""Reader for the Carve-generated dlt provenance header.

Files generated by Carve's EL agent (dlt-engineer, Increment 3) carry a
leading comment block recording where the code came from. This module
*reads* that block into structured metadata; the *writing* is the EL
agent's job and is out of scope here. The reader is consumed by other
capabilities — e.g. the lineage spec's ``dlt_schema`` reader uses the
``destination`` binding during investigation, and any future provenance
view.

Concrete header shape (spec *Provenance header convention*)::

    # ─────────────────────────────────────────────────────────────────
    # Generated by Carve from carve/sources/stripe at commit abc1234.
    # Customized for destination "snowflake.raw_stripe".
    # Generated: 2026-05-19T14:23:01Z
    # Plan: plan_a1b2c3d4
    # Build: build_e5f6g7h8
    # Do not edit this header. Edits below the header are preserved on regenerate.
    # ─────────────────────────────────────────────────────────────────

Robustness contract:

* **Every field is optional.** A header missing the ``Plan:`` line still
  parses — the field is ``None``, never a parse failure. This keeps the
  reader forward/backward compatible as the header evolves.
* **Headerless files are user-authored.** A file whose first comment
  lines don't contain the ``Generated by Carve`` marker is reported via
  :func:`is_carve_generated` returning ``False`` /
  :func:`parse_provenance_header` returning ``None``. The agent never
  modifies such files (orchestration-only artifacts).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

# The marker that identifies a Carve-generated header. Its presence in the
# leading comment block is what distinguishes generated from user-authored
# files. The `from <source> at commit <sha>` tail is captured
# opportunistically — the commit token runs up to a period or whitespace so
# the trailing "." in the sentence isn't swept into the SHA. No end-of-line
# anchor: this is matched against the whole (joined) comment block.
_GENERATED_RE = re.compile(
    r"Generated by Carve"
    r"(?:\s+from\s+(?P<source>\S+?)\s+at commit\s+(?P<commit>[^\s.]+))?"
)
_DESTINATION_RE = re.compile(r'Customized for destination\s+"(?P<destination>[^"]+)"')
_GENERATED_AT_RE = re.compile(r"Generated:\s*(?P<generated_at>\S+)")
_PLAN_RE = re.compile(r"Plan:\s*(?P<plan_id>\S+)")
_BUILD_RE = re.compile(r"Build:\s*(?P<build_id>\S+)")

# How many leading lines to scan for the header. The block is a handful of
# lines at the very top; bounding the scan keeps it cheap on large files and
# avoids matching a stray "Generated by Carve" deep in the body.
_MAX_HEADER_LINES = 20


@dataclass(frozen=True)
class ProvenanceHeader:
    """Structured metadata parsed from a Carve provenance header.

    Every field is optional: a field absent from (or unparseable in) the
    header is ``None``. ``raw`` holds the verbatim comment lines so
    callers can surface the original block.

    * ``source`` — the curated-library / source path the file was
      generated from (e.g. ``carve/sources/stripe``).
    * ``commit`` — the source commit the generation was pinned to.
    * ``destination`` — the destination binding (e.g.
      ``snowflake.raw_stripe``).
    * ``generated_at`` — the ISO-8601 generation timestamp, as a string
      (not parsed into a ``datetime`` — callers decide).
    * ``plan_id`` / ``build_id`` — the plan and build the generation
      belonged to.
    """

    source: str | None = None
    commit: str | None = None
    destination: str | None = None
    generated_at: str | None = None
    plan_id: str | None = None
    build_id: str | None = None
    raw: tuple[str, ...] = ()


def is_carve_generated(content: str) -> bool:
    """Return ``True`` if ``content`` begins with a Carve provenance header.

    Scans only the leading comment block (the first :data:`_MAX_HEADER_LINES`
    lines) for the ``Generated by Carve`` marker. Files without it are
    user-authored.
    """
    for line in _leading_comment_lines(content):
        if _GENERATED_RE.search(line):
            return True
    return False


def parse_provenance_header(content: str) -> ProvenanceHeader | None:
    """Parse the provenance header from file ``content``.

    Returns a :class:`ProvenanceHeader` if the leading comment block is a
    Carve-generated header (even a partial one — missing fields become
    ``None``), or ``None`` if the file is user-authored (no marker). Never
    raises on a malformed header; unrecognized lines are simply ignored.
    """
    header_lines = _leading_comment_lines(content)
    if not any(_GENERATED_RE.search(line) for line in header_lines):
        return None

    blob = "\n".join(header_lines)
    gen = _GENERATED_RE.search(blob)
    dest = _DESTINATION_RE.search(blob)
    gen_at = _GENERATED_AT_RE.search(blob)
    plan = _PLAN_RE.search(blob)
    build = _BUILD_RE.search(blob)

    return ProvenanceHeader(
        source=gen.group("source") if gen else None,
        commit=gen.group("commit") if gen else None,
        destination=dest.group("destination") if dest else None,
        generated_at=gen_at.group("generated_at") if gen_at else None,
        plan_id=plan.group("plan_id") if plan else None,
        build_id=build.group("build_id") if build else None,
        raw=tuple(header_lines),
    )


def parse_provenance_file(path: Path) -> ProvenanceHeader | None:
    """Read ``path`` and parse its provenance header.

    Convenience wrapper over :func:`parse_provenance_header`. A file that
    can't be read as UTF-8 text (e.g. a binary artifact) is treated as
    user-authored and returns ``None`` rather than raising.
    """
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None
    return parse_provenance_header(content)


def _leading_comment_lines(content: str) -> list[str]:
    """Return the leading ``#``-comment lines (stripped of the ``#`` prefix).

    Stops at the first non-comment, non-blank line so the body is never
    scanned. Blank lines inside the comment block are kept as empty
    strings (so a header separated from a blank line still parses); a
    leading shebang is skipped.
    """
    lines: list[str] = []
    for index, raw_line in enumerate(content.splitlines()):
        stripped = raw_line.strip()
        if index == 0 and stripped.startswith("#!"):
            continue  # shebang
        if not stripped:
            if lines:
                lines.append("")  # interior blank within the comment block
            continue
        if not stripped.startswith("#"):
            break  # reached code; the header (if any) is above
        lines.append(stripped.lstrip("#").strip())
        if len(lines) >= _MAX_HEADER_LINES:
            break
    return lines


__all__ = [
    "ProvenanceHeader",
    "is_carve_generated",
    "parse_provenance_file",
    "parse_provenance_header",
]
