"""Tests for the provenance header reader.

The reader must: parse a full header cleanly; surface missing fields as
``None`` (never a parse failure); and report headerless files as
user-authored.

*(layout spec Tests: unit bullet 4)*
"""

from __future__ import annotations

from pathlib import Path

from carve.integrations.provenance import (
    is_carve_generated,
    parse_provenance_file,
    parse_provenance_header,
)

_FULL_HEADER = """\
# ─────────────────────────────────────────────────────────────────────
# Generated by Carve from carve/sources/stripe at commit abc1234.
# Customized for destination "snowflake.raw_stripe".
# Generated: 2026-05-19T14:23:01Z
# Plan: plan_a1b2c3d4
# Build: build_e5f6g7h8
# Do not edit this header. Edits below the header are preserved on regenerate.
# ─────────────────────────────────────────────────────────────────────

import dlt


@dlt.source
def stripe():
    ...
"""


def test_full_header_parses_all_fields() -> None:
    header = parse_provenance_header(_FULL_HEADER)
    assert header is not None
    assert header.source == "carve/sources/stripe"
    assert header.commit == "abc1234"
    assert header.destination == "snowflake.raw_stripe"
    assert header.generated_at == "2026-05-19T14:23:01Z"
    assert header.plan_id == "plan_a1b2c3d4"
    assert header.build_id == "build_e5f6g7h8"


def test_is_carve_generated_true_for_full_header() -> None:
    assert is_carve_generated(_FULL_HEADER) is True


def test_missing_fields_are_none_not_failure() -> None:
    # Only the marker line + a destination; everything else absent.
    partial = (
        "# Generated by Carve from carve/sources/foo at commit deadbee.\n"
        '# Customized for destination "snowflake.raw_foo".\n'
        "\nimport dlt\n"
    )
    header = parse_provenance_header(partial)
    assert header is not None
    assert header.source == "carve/sources/foo"
    assert header.commit == "deadbee"
    assert header.destination == "snowflake.raw_foo"
    # The absent lines come back as None rather than raising.
    assert header.generated_at is None
    assert header.plan_id is None
    assert header.build_id is None


def test_marker_only_header_parses_with_all_optional_none() -> None:
    header = parse_provenance_header("# Generated by Carve.\n\nimport dlt\n")
    assert header is not None
    assert header.source is None
    assert header.commit is None
    assert header.destination is None
    assert header.plan_id is None


def test_headerless_file_is_user_authored() -> None:
    user_file = "import dlt\n\n@dlt.source\ndef hand_written():\n    ...\n"
    assert parse_provenance_header(user_file) is None
    assert is_carve_generated(user_file) is False


def test_comment_that_is_not_carve_header_is_user_authored() -> None:
    # A leading comment block that isn't a Carve header doesn't match.
    other = "# My own notes about this file.\n# TODO: refactor.\n\nimport dlt\n"
    assert parse_provenance_header(other) is None


def test_marker_deep_in_body_is_not_treated_as_header() -> None:
    # "Generated by Carve" appearing far below the leading comment block
    # (i.e. in code/strings) must not be picked up as a header.
    body = "import dlt\n\n" + "\n".join(f"x{i} = {i}" for i in range(30))
    body += '\nNOTE = "Generated by Carve from x at commit y."\n'
    assert parse_provenance_header(body) is None


def test_shebang_is_skipped() -> None:
    content = (
        "#!/usr/bin/env python\n"
        "# Generated by Carve from carve/sources/foo at commit abc.\n"
        "\nimport dlt\n"
    )
    header = parse_provenance_header(content)
    assert header is not None
    assert header.source == "carve/sources/foo"


def test_parse_provenance_file_reads_from_disk(tmp_path: Path) -> None:
    f = tmp_path / "stripe.py"
    f.write_text(_FULL_HEADER, encoding="utf-8")
    header = parse_provenance_file(f)
    assert header is not None
    assert header.build_id == "build_e5f6g7h8"


def test_parse_provenance_file_missing_file_is_none(tmp_path: Path) -> None:
    assert parse_provenance_file(tmp_path / "nope.py") is None


def test_raw_lines_preserved(tmp_path: Path) -> None:
    header = parse_provenance_header(_FULL_HEADER)
    assert header is not None
    assert any("Generated by Carve" in line for line in header.raw)
