"""OSS packaging helpers for `carve init`.

The bundled Postgres `docker-compose.yml` template, the project slug used to
keep multiple projects' containers/volumes from colliding, external-Postgres
URL validation, and the Docker availability check.

See specs/capabilities/packaging.md. The bundle is **Postgres-only** — Carve
itself runs natively via `carve serve`, not in a container.
"""

from __future__ import annotations

import hashlib
import re
import shutil

# Pin the Postgres major (not `latest`) so existing installs don't get a
# surprise upgrade. Bump when a newer major has proven out.
POSTGRES_IMAGE = "postgres:16"

# The bundled Postgres connection string. Matches the compose service below
# (host port 5432, user/db `carve`); bound to 127.0.0.1 only.
BUNDLED_DATABASE_URL = "postgresql+psycopg://carve:carve@127.0.0.1:5432/carve"

_COMPOSE_TEMPLATE = """\
# Generated by `carve init`. Edit freely; carve will not regenerate this file
# on subsequent init runs unless you delete it first.
services:
  carve-postgres:
    image: {image}
    container_name: carve-postgres-{slug}
    environment:
      POSTGRES_USER: carve
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:-carve}}
      POSTGRES_DB: carve
    volumes:
      - carve-postgres-data:/var/lib/postgresql/data
    ports:
      # Bound to localhost only; never exposed to the network.
      - "127.0.0.1:${{CARVE_POSTGRES_PORT:-5432}}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carve -d carve"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  carve-postgres-data:
    name: carve-postgres-data-{slug}
"""


class InvalidPostgresUrlError(ValueError):
    """Raised when an `--external-postgres` connection string is malformed."""


def project_slug(project_name: str) -> str:
    """Slugify a project directory name for container/volume names.

    Lowercased; every run of non-alphanumeric characters collapses to a
    single hyphen; leading/trailing hyphens are stripped.

    Names that slug to empty (all non-ASCII, e.g. CJK, or punctuation-only)
    get a stable ``carve-<hash>`` suffix derived from the original name, so
    two such projects still get distinct container/volume names rather than
    both collapsing to a bare ``carve``.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", project_name.lower()).strip("-")
    if slug:
        return slug
    digest = hashlib.sha1(project_name.encode("utf-8")).hexdigest()[:8]
    return f"carve-{digest}"


def render_compose(project_name: str) -> str:
    """Render the bundled Postgres ``docker-compose.yml`` for ``project_name``."""
    return _COMPOSE_TEMPLATE.format(
        image=POSTGRES_IMAGE, slug=project_slug(project_name)
    )


def normalize_postgres_url(url: str) -> str:
    """Validate + normalize an ``--external-postgres`` URL.

    ``postgresql+psycopg://…`` is returned unchanged; ``postgresql://…`` is
    upgraded to the explicit ``+psycopg`` driver form. Anything else raises
    :class:`InvalidPostgresUrlError`.
    """
    url = url.strip()
    if url.startswith("postgresql+psycopg://"):
        return url
    if url.startswith("postgresql://"):
        return "postgresql+psycopg://" + url[len("postgresql://") :]
    shown = url[:24] + "…" if len(url) > 24 else url
    raise InvalidPostgresUrlError(
        "Connection string must start with postgresql+psycopg:// or "
        f"postgresql:// (got {shown!r})."
    )


def docker_compose_available() -> bool:
    """True when a ``docker`` CLI is on PATH (a proxy for ``docker compose``)."""
    return shutil.which("docker") is not None


def bundled_env_block() -> str:
    """The ``.env.example`` state-store section for the bundled-Postgres path."""
    return (
        "\n# === State store ===\n"
        "# Defaults match the bundled docker-compose.yml. Override if you use\n"
        "# an external Postgres (managed RDS, Cloud SQL, Supabase, etc.).\n"
        f"DATABASE_URL={BUNDLED_DATABASE_URL}\n"
        '# Override the bundled Postgres password (default "carve", local dev only):\n'
        "# POSTGRES_PASSWORD=\n"
        "# Override the bundled Postgres host port (default 5432):\n"
        "# CARVE_POSTGRES_PORT=\n"
    )


def external_env_block() -> str:
    """The ``.env.example`` state-store section for an external Postgres.

    Only a **commented placeholder** — the real, password-bearing URL is never
    written to ``.env.example`` (which is conventionally committed to git).
    ``carve init`` prints the real line for the user to paste into their
    gitignored ``.env``.
    """
    return (
        "\n# === State store (external Postgres) ===\n"
        "# Set DATABASE_URL in your .env (gitignored) to your Postgres URL.\n"
        "# Carve does not manage this instance — backups, upgrades, and tuning\n"
        "# are your responsibility.\n"
        "# DATABASE_URL=postgresql+psycopg://USER:PASSWORD@HOST:5432/DB\n"
    )
