"""Integration: extract-load agent against a stubbed plan task.

Drives `run_extract_load_agent` end-to-end with a mocked Anthropic
client (the same harness style used in
`tests/core/skills/test_plan_agent_integration.py`), verifies that
file output lands under `el/<name>/`, and asserts the
`submit_step` payload's `file_list` matches the task's
`expected_outputs`.

The build-flow wrapper (P1-02 / `builder.py`) currently calls
`m1_build_agent` for backwards compatibility — that's the "minimal"
build-flow integration choice noted in the phase doc. The new
`run_extract_load_agent` callable is wired in here for direct
invocation, which is what P1-07 / P1-09 will consume; switching the
default code path lives in P1-07 (the el-deploy story).
"""

from __future__ import annotations

import copy
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from unittest.mock import MagicMock

import pytest

from carve.core.agents.extract_load.agent import run_extract_load_agent
from carve.core.config.schema import (
    Config,
    ConnectionsConfig,
    ModelsConfig,
    ProjectConfig,
    RunnerConfig,
    ServerConfig,
)
from carve.core.config.schema import SnowflakeConnection as ConnConfig


def _usage() -> SimpleNamespace:
    return SimpleNamespace(
        input_tokens=10,
        output_tokens=5,
        cache_creation_input_tokens=0,
        cache_read_input_tokens=0,
    )


def _config() -> Config:
    return Config(
        project=ProjectConfig(name="el-flow"),
        models=ModelsConfig(anthropic_api_key="sk-test"),
        runner=RunnerConfig(),
        server=ServerConfig(state_store="sqlite:///:memory:"),
        connections=ConnectionsConfig(
            snowflake={
                "dev": ConnConfig(
                    account="acct",
                    user="u",
                    password="p",
                    role="TRANSFORMER_DEV",
                    warehouse="W",
                    database="ANALYTICS_DEV",
                )
            }
        ),
        config_hash="0123456789abcdef",
    )


def _task() -> dict[str, Any]:
    return {
        "step": 1,
        "agent": "extract_load",
        "action": "generate_extractor",
        "inputs": {
            "artifact_name": "events_ingest",
            "goal": "Daily ingest of events into RAW.EVENTS.",
            "source": {
                "type": "http_csv",
                "url": "https://example.com/events.csv",
            },
            "destination": {
                "database": "ANALYTICS_DEV",
                "schema": "RAW",
                "table": "EVENTS",
                "primary_key": "ID",
            },
            "transformation": {
                "strategy": "merge_upsert",
                "rationale": "PK upsert.",
            },
            "columns": [
                {"name": "ID", "type": "NUMBER", "nullable": False},
                {"name": "EVENT_NAME", "type": "VARCHAR(255)", "nullable": True},
            ],
        },
        "expected_outputs": [
            {"path": "el/events_ingest/main.py", "kind": "create"},
            {
                "path": "el/events_ingest/requirements.txt",
                "kind": "create",
            },
            {"path": "el/events_ingest/snowflake.sql", "kind": "create"},
        ],
    }


def _scripted_client() -> MagicMock:
    """Build a client whose three writes mirror the task's expected_outputs."""
    main_py = (
        "import os\n"
        "import requests\n"
        "import snowflake.connector\n"
        "\n"
        "def main():\n"
        "    conn = snowflake.connector.connect(\n"
        "        user=os.environ['DEV_SNOWFLAKE_USER'],\n"
        "        password=os.environ['DEV_SNOWFLAKE_PASSWORD'],\n"
        "        account=os.environ['DEV_SNOWFLAKE_ACCOUNT'],\n"
        "        role=os.environ['DEV_SNOWFLAKE_ROLE'],\n"
        "        warehouse=os.environ['DEV_SNOWFLAKE_WAREHOUSE'],\n"
        "        database=os.environ['DEV_SNOWFLAKE_DATABASE'],\n"
        "        schema=os.environ['DEV_SNOWFLAKE_SCHEMA'],\n"
        "        paramstyle='qmark',\n"
        "    )\n"
        "    print('[done] total_rows=0')\n"
    )
    requirements_txt = "snowflake-connector-python==3.7.1\nrequests==2.31.0\n"
    ddl_sql = (
        "-- Auto-generated by carve build for pipeline events_ingest "
        "(target: dev).\n"
        "-- Applied by `carve el deploy events_ingest --from <X> --to dev`.\n"
        "-- All statements are idempotent; re-running is safe.\n\n"
        "-- === Schema ===\n"
        "CREATE SCHEMA IF NOT EXISTS ANALYTICS_DEV.RAW;\n\n"
        "-- === Table ===\n"
        "CREATE TABLE IF NOT EXISTS ANALYTICS_DEV.RAW.EVENTS (\n"
        "    ID NUMBER NOT NULL,\n"
        "    EVENT_NAME VARCHAR(255),\n"
        "    PRIMARY KEY (ID)\n"
        ");\n\n"
        "-- === Grants ===\n"
        "GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "
        "ANALYTICS_DEV.RAW.EVENTS TO ROLE TRANSFORMER_DEV;\n"
    )

    def tu(name: str, input_: dict[str, Any], tid: str) -> SimpleNamespace:
        return SimpleNamespace(type="tool_use", id=tid, name=name, input=input_)

    def resp(content: list[Any]) -> SimpleNamespace:
        return SimpleNamespace(content=content, stop_reason="tool_use", usage=_usage())

    base = "el/events_ingest"
    responses = [
        resp([tu("write_file", {"path": f"{base}/main.py", "content": main_py}, "tu_1")]),
        resp(
            [
                tu(
                    "write_file",
                    {
                        "path": f"{base}/requirements.txt",
                        "content": requirements_txt,
                    },
                    "tu_2",
                )
            ]
        ),
        resp(
            [
                tu(
                    "write_file",
                    {
                        "path": "el/events_ingest/snowflake.sql",
                        "content": ddl_sql,
                    },
                    "tu_3",
                )
            ]
        ),
        resp(
            [
                tu(
                    "submit_step",
                    {
                        "file_list": [
                            f"{base}/main.py",
                            f"{base}/requirements.txt",
                            "el/events_ingest/snowflake.sql",
                        ],
                        "summary": "Wrote events_ingest extractor + DDL.",
                        "error": False,
                    },
                    "tu_4",
                )
            ]
        ),
    ]
    client = MagicMock()
    snapshots: list[dict[str, Any]] = []
    response_iter = iter(responses)

    def _create(**kwargs: Any) -> Any:
        snapshots.append(copy.deepcopy(kwargs))
        return next(response_iter)

    client.messages.create.side_effect = _create
    client.calls = snapshots
    return client


@pytest.fixture
def project_dir(tmp_path: Path) -> Path:
    (tmp_path / "el").mkdir(parents=True, exist_ok=True)
    return tmp_path


def test_extract_load_flow_end_to_end(project_dir: Path) -> None:
    task = _task()
    client = _scripted_client()
    result = run_extract_load_agent(
        task=task,
        active_target="dev",
        config=_config(),
        project_dir=project_dir,
        client=client,
        max_turns=10,
    )
    # File output lands under the flat el/ tree (P1.1-01).
    base = project_dir / "el/events_ingest"
    assert (base / "main.py").is_file()
    assert (base / "requirements.txt").is_file()
    assert (base / "snowflake.sql").is_file()

    # submit_step payload matches expected_outputs (modulo ordering).
    expected_paths = {
        entry["path"] for entry in task["expected_outputs"] if isinstance(entry, dict)
    }
    assert set(result.file_list) == expected_paths
    assert result.success is True
    assert "events_ingest" in result.summary.lower()
