"""Write the Carve provenance header that :mod:`carve.integrations.provenance` reads.

Every Carve-generated dlt file (a curated-library copy, a native scaffold)
carries a leading comment block recording where the code came from. The
*reader* shipped earlier; this is the *writer* the DLT engineer uses so every
file it emits is properly headered. Header and body round-trip:
``parse_provenance_header(with_provenance_header(body, ...))`` recovers the
fields, and the body below the header is left verbatim (the engineer's edits
are preserved on regenerate).

Round-trip constraints (matching the reader's grammar): ``source`` must be a
single token (no spaces — it's a path like ``carve/sources/stripe``) and
``commit`` must be dot-free (a git SHA, not a ``v1.2.3`` tag); the reader stops
those captures at the first space / period respectively. Carve produces exactly
those shapes; the reader's broader-input handling is tracked separately.
"""

from __future__ import annotations

from datetime import UTC, datetime

from carve.integrations.provenance import is_carve_generated

# A plain-ASCII rule (the reader keys off the "Generated by Carve" marker, not
# the rule — ASCII avoids ambiguous-unicode lint and renders everywhere).
_RULE = "# " + "-" * 70
_DO_NOT_EDIT = "# Do not edit this header. Edits below the header are preserved on regenerate."


def emit_provenance_header(
    *,
    source: str | None = None,
    commit: str | None = None,
    destination: str | None = None,
    generated_at: datetime | str | None = None,
    plan_id: str | None = None,
    build_id: str | None = None,
) -> str:
    """Render the provenance header comment block (every field optional).

    ``generated_at`` accepts a ``datetime`` (rendered ISO-8601), a string (used
    verbatim), or ``None`` (stamped with the current UTC time).
    """
    marker = "Generated by Carve"
    if source and commit:
        marker += f" from {source} at commit {commit}."
    elif source:
        marker += f" from {source}."
    lines = [_RULE, f"# {marker}"]
    if destination:
        lines.append(f'# Customized for destination "{destination}".')
    lines.append(f"# Generated: {_stamp(generated_at)}")
    if plan_id:
        lines.append(f"# Plan: {plan_id}")
    if build_id:
        lines.append(f"# Build: {build_id}")
    lines += [_DO_NOT_EDIT, _RULE]
    return "\n".join(lines) + "\n"


def with_provenance_header(body: str, **fields: object) -> str:
    """Prepend a provenance header to ``body``.

    If ``body`` already carries a Carve header it is returned unchanged (the
    modify path preserves an existing header via ``edit``; never double-stamp).
    """
    if is_carve_generated(body):
        return body
    header = emit_provenance_header(**fields)  # type: ignore[arg-type]
    if not body:
        return header
    sep = "" if body.startswith("\n") else "\n"
    return f"{header}{sep}{body}"


def _stamp(value: datetime | str | None) -> str:
    if isinstance(value, str):
        return value
    moment = value if isinstance(value, datetime) else datetime.now(UTC)
    return moment.isoformat()


__all__ = ["emit_provenance_header", "with_provenance_header"]
