name: DCO

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  dco-check:
    name: DCO sign-off check
    runs-on: ubuntu-latest
    steps:
      - name: Check commits for DCO sign-off
        uses: tim-actions/dco@2fd0504dc0d27b33f542867c300c60840c6dcb20
